name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# NOTE(Jack): We use the scope tags (https://docs.docker.com/build/cache/backends/gha/#scope) here to preserve the cache
# for each step. Otherwise it will by default use the same scope for all jobs and only preserve the last cache item.
# NOTE(Jack): My finding is that the critical step to effectively get docker caching is to set the scope in the
# "cache-from" and "cache-to" instruction. If this is not done then the default "buildkit" scope is used on only the
# last cached item is saved, which doesn't do us any good. Read the docs here
# (https://docs.docker.com/build/cache/backends/gha/#scope) for the official explanation.
#
# Our strategy at time of writing (17.11.2025) is to have the code checks isolated in their own scope because they have
# no dependency on the rest of the build. The debug build will push and pull from its own scope because there are a lot
# of built and installed dependencies there which can be cached. And finally the code coverage stage will pull from the
# debug build cache, but not actually push any cache, because there is nothing really to cache there.
#
# Also note that we use the "needs" tag to explicitly setup dependencies between stages so that if the code checks fail
# nothing else happens and we do not waste server time.
jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: code-checks-stage
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha,scope=code-checks
          cache-to: type=gha,mode=max,scope=code-checks
          file: building/Dockerfile
          tags: reprojection-code-checks:latest
          target: code-checks-stage
  debug-build:
    needs: code-checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: debug-build-stage
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha,scope=debug-build
          cache-to: type=gha,mode=max,scope=debug-build
          file: building/Dockerfile
          tags: reprojection-debug-build:latest
          target: debug-build-stage
  code-coverage-assertion:
    needs: debug-build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: code-coverage-assertion-stage
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha,scope=debug-build
          file: building/Dockerfile
          tags: reprojection-code-coverage-assertion:latest
          target: code-coverage-assertion-stage
  python-tooling:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/roim/docker-action-lfs/blob/main/.github/workflows/custom-context--working.yml
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: git lfs pull
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: python-tooling-stage
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha,scope=python-tooling
          cache-to: type=gha,mode=max,scope=python-tooling
          file: building/Dockerfile
          tags: reprojection-python-tooling:latest
          target: python-tooling-stage
          context: .