name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# NOTE(Jack): We use the scope tags (https://docs.docker.com/build/cache/backends/gha/#scope) here to preserve the cache
# for each step. Otherwise it will by default use the same scope for all jobs and only preserve the last cache item.
jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: code-checks-stage
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha,scope=code-checks
          cache-to: type=gha,mode=max,scope=code-checks
          file: building/Dockerfile
          tags: reprojection-code-checks:latest
          target: code-checks-stage
  debug-build:
    needs: code-checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: debug-build-stage
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha,scope=debug-build
          cache-to: type=gha,mode=max,scope=debug-build
          file: building/Dockerfile
          tags: reprojection-debug-build:latest
          target: debug-build-stage
  code-coverage-assertion:
    needs: debug-build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: code-coverage-assertion-stage
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha,scope=debug-build
          cache-to: type=gha,mode=max,scope=code-coverage-assertion
          file: building/Dockerfile
          tags: reprojection-code-coverage-assertion:latest
          target: code-coverage-assertion-stage